language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - TRAVIS=true

services:
  - mysql

before_script:
  - composer install
  - mysql -e 'create database IF NOT EXISTS test';

script: composer test
